### ISSUE TITLE
the sounds stops playing after a few seconds

### ISSUE THREAD

**Issue by gaurav1903** [londonappbrewery/xylophone-flutter#20]
after I play with the buttons and quickly press them a few times. all the buttons completely stop working. My code was the same as ms angela. I had to earlier move my project into new android embedding.

**Comment by MdRubayat** [comment]
I'm facing the exact same issue here . After few clicks the buttons stops working, does anyone have any solutions for this .

**Comment by ArchangelAmin** [comment]
same issue here, I have run the app multiple times and counted and after about 31 button presses the app stops working.

**Comment by akhil-muralidharan** [comment]
[SOLUTION]

modify playSound() function as below.

  void playSound(int note) async {
    final player = AudioCache();
    var bytes = await (await player.load('note$note.wav')).readAsBytes();
    player.playBytes(bytes);
  }

**Comment by gaurav1903** [comment]
thanks bro. But do you have any idea, why this happens??

**Comment by ArchangelAmin** [comment]
> [SOLUTION]
> 
> modify playSound() function as below.
> 
> void playSound(int note) async {
> final player = AudioCache();
> var bytes = await (await player.load('note$note.wav')).readAsBytes();
> player.playBytes(bytes);
> }

thanks.
I'm not a programmer and I don't know why and how it works, but it works!

**Comment by ArchangelAmin** [comment]
> thanks bro. But do you have any idea, why this happens??

https://github.com/luanpotter/audioplayers/issues/682#issuecomment-737195863

here is a short explanation from a collaborator on the project. hope this helps.

**Comment by keymistress** [comment]
> [SOLUTION]
> 
> modify playSound() function as below.
> 
> void playSound(int note) async {
> final player = AudioCache();
> var bytes = await (await player.load('note$note.wav')).readAsBytes();
> player.playBytes(bytes);
> }

I really want it to work but I'm getting new errors with your code modification though...

```
V/MediaPlayer(24737): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(24737): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaPlayer(24737): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(24737): cleanDrmObj: mDrmObj=null mDrmSessionId=null
E/MediaPlayerNative(24737): error (1, -2147483648)
E/MediaPlayer(24737): Error (1,-2147483648)
E/MediaPlayerNative(24737): stop called in state 0, mPlayer(0xaf5811b0)
E/MediaPlayerNative(24737): error (-38, 0)
V/MediaPlayer(24737): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(24737): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaPlayer(24737): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(24737): cleanDrmObj: mDrmObj=null mDrmSessionId=null
I/rrow.xylophone(24737): Background concurrent copying GC freed 11765(657KB) AllocSpace objects, 19(10MB) LOS objects, 49% free, 15MB/30MB, paused 2.119ms total 177.047ms
V/MediaPlayer(24737): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(24737): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaPlayer(24737): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(24737): cleanDrmObj: mDrmObj=null mDrmSessionId=null
```
