### ISSUE TITLE
Audio tag error

### ISSUE THREAD

**Issue by khanadnan10** [londonappbrewery/xylophone-flutter#47]
I'm using the new version of flutter 3.0.5 and here is the error.
![image](https://user-images.githubusercontent.com/84623555/186774773-070dcf28-a4a7-482e-a4b2-64cb77252a53.png)
I've tried using different solutions but the results were not solving the issue.

**Comment by khanadnan10** [comment]
Done!

**Comment by ketan2jangid** [comment]
@khanadnan10 I am facing similar issue, first the Audiocache didn't had any play method so I am using the AudioPlayer now. But still I am not able to resolve the issue, can you please help?

![image](https://user-images.githubusercontent.com/92528845/203340314-83a30eeb-7b28-46a7-8d1a-121902f97edb.png)
