### ISSUE TITLE
i need some help i can't run xylophone-flutter

### ISSUE THREAD

**Issue by krit-Okoye** [londonappbrewery/xylophone-flutter#6]
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
  Output:  C:\xylophone-flutter\build\app\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:186: error: resource android:attr/fontVariationSettings not found.
  C:\xylophone-flutter\build\app\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:187: error: resource android:attr/ttcIndex not found.
  error: failed linking references.

  Command: C:\Users\user\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.1-4818971-windows.jar\ed5d63241c32b03b627a8ec4203b323c\aapt2-3.2.1-4818971-windows\aapt2.exe link -I\
          C:\Users\user\AppData\Local\Android\sdk\platforms\android-27\android.jar\
          --manifest\
          C:\xylophone-flutter\build\app\intermediates\merged_manifests\debug\processDebugManifest\merged\AndroidManifest.xml\
          -o\
          C:\xylophone-flutter\build\app\intermediates\processed_res\debug\processDebugResources\out\resources-debug.ap_\
          -R\
          @C:\xylophone-flutter\build\app\intermediates\incremental\processDebugResources\resources-list-for-resources-debug.ap_.txt\
          --auto-add-overlay\
          --java\
          C:\xylophone-flutter\build\app\generated\not_namespaced_r_class_sources\debug\processDebugResources\r\
          --custom-package\
          co.appbrewery.xylophone\
          -0\
          apk\
          --output-text-symbols\
          C:\xylophone-flutter\build\app\intermediates\symbols\debug\R.txt\
          --no-version-vectors
  Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #0
  Output:  C:\Users\user\.gradle\caches\transforms-1\files-1.1\support-compat-28.0.0.aar\81bcf9a7fa6cfeeb7c44abcfdc197db5\res\values\values.xml:89:5-125:25: AAPT: error: resource android:attr/fontVariationSettings not found.

  C:\Users\user\.gradle\caches\transforms-1\files-1.1\support-compat-28.0.0.aar\81bcf9a7fa6cfeeb7c44abcfdc197db5\res\values\values.xml:89:5-125:25: AAPT: error: resource android:attr/ttcIndex not found.

  error: failed linking references.
  Command: C:\Users\user\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.1-4818971-windows.jar\ed5d63241c32b03b627a8ec4203b323c\aapt2-3.2.1-4818971-windows\aapt2.exe link -I\
          C:\Users\user\AppData\Local\Android\sdk\platforms\android-27\android.jar\
          --manifest\
          C:\xylophone-flutter\build\app\intermediates\merged_manifests\debug\processDebugManifest\merged\AndroidManifest.xml\
          -o\
          C:\xylophone-flutter\build\app\intermediates\processed_res\debug\processDebugResources\out\resources-debug.ap_\
          -R\
          @C:\xylophone-flutter\build\app\intermediates\incremental\processDebugResources\resources-list-for-resources-debug.ap_.txt\
          --auto-add-overlay\
          --java\
          C:\xylophone-flutter\build\app\generated\not_namespaced_r_class_sources\debug\processDebugResources\r\
          --custom-package\
          co.appbrewery.xylophone\
          -0\
          apk\
          --output-text-symbols\
          C:\xylophone-flutter\build\app\intermediates\symbols\debug\R.txt\
          --no-version-vectors
  Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by krit-Okoye** [comment]
i try run a  --stacktrace and --info --debug --scan but it not work

**Comment by mahmunk** [comment]
Getting same error. - also get the error in your other projects

**Comment by GUIEEN** [comment]
https://stackoverflow.com/questions/49208772/error-resource-androidattr-fontvariationsettings-not-found
Change CompileSdkVersion -> 28

**Comment by TheMuellenator** [comment]
Thanks for raising this. Updated the project. Should work now.
